package test_models

const FAKE_PUSH_HEADER = `Request URL: http://houseoffeeder.ddns.net:9090/githubUpdate
Request method: POST
Accept: */*
Content-Type: application/x-www-form-urlencoded
User-Agent: GitHub-Hookshot/86b410b
X-GitHub-Delivery: b8c2de28-fa74-11ee-97e0-142f5d2242e4
X-GitHub-Event: push
X-GitHub-Hook-ID: 468207434
X-GitHub-Hook-Installation-Target-ID: 713630393
X-GitHub-Hook-Installation-Target-Type: repository`

const FAKE_PUSH_BODY = `{
	"ref": "refs/heads/test-commits",
	"before": "6ab28d2aded0e6f91ec21f629471a08286f1a40c",
	"after": "0000000000000000000000000000000000000000",
	"repository": {
	  "id": 713630393,
	  "node_id": "R_kgDOKokiuQ",
	  "name": "21Updater",
	  "full_name": "feed3r/21Updater",
	  "private": false,
	  "owner": {
		"name": "feed3r",
		"email": "feeder81@gmail.com",
		"login": "feed3r",
		"id": 4531376,
		"node_id": "MDQ6VXNlcjQ1MzEzNzY=",
		"avatar_url": "https://avatars.githubusercontent.com/u/4531376?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/feed3r",
		"html_url": "https://github.com/feed3r",
		"followers_url": "https://api.github.com/users/feed3r/followers",
		"following_url": "https://api.github.com/users/feed3r/following{/other_user}",
		"gists_url": "https://api.github.com/users/feed3r/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/feed3r/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/feed3r/subscriptions",
		"organizations_url": "https://api.github.com/users/feed3r/orgs",
		"repos_url": "https://api.github.com/users/feed3r/repos",
		"events_url": "https://api.github.com/users/feed3r/events{/privacy}",
		"received_events_url": "https://api.github.com/users/feed3r/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/feed3r/21Updater",
	  "description": "Some experiments in creating a Telegram BOT to receive the updates from a GitHub (in particular, from THIS repository)",
	  "fork": false,
	  "url": "https://github.com/feed3r/21Updater",
	  "forks_url": "https://api.github.com/repos/feed3r/21Updater/forks",
	  "keys_url": "https://api.github.com/repos/feed3r/21Updater/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/feed3r/21Updater/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/feed3r/21Updater/teams",
	  "hooks_url": "https://api.github.com/repos/feed3r/21Updater/hooks",
	  "issue_events_url": "https://api.github.com/repos/feed3r/21Updater/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/feed3r/21Updater/events",
	  "assignees_url": "https://api.github.com/repos/feed3r/21Updater/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/feed3r/21Updater/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/feed3r/21Updater/tags",
	  "blobs_url": "https://api.github.com/repos/feed3r/21Updater/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/feed3r/21Updater/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/feed3r/21Updater/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/feed3r/21Updater/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/feed3r/21Updater/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/feed3r/21Updater/languages",
	  "stargazers_url": "https://api.github.com/repos/feed3r/21Updater/stargazers",
	  "contributors_url": "https://api.github.com/repos/feed3r/21Updater/contributors",
	  "subscribers_url": "https://api.github.com/repos/feed3r/21Updater/subscribers",
	  "subscription_url": "https://api.github.com/repos/feed3r/21Updater/subscription",
	  "commits_url": "https://api.github.com/repos/feed3r/21Updater/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/feed3r/21Updater/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/feed3r/21Updater/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/feed3r/21Updater/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/feed3r/21Updater/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/feed3r/21Updater/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/feed3r/21Updater/merges",
	  "archive_url": "https://api.github.com/repos/feed3r/21Updater/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/feed3r/21Updater/downloads",
	  "issues_url": "https://api.github.com/repos/feed3r/21Updater/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/feed3r/21Updater/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/feed3r/21Updater/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/feed3r/21Updater/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/feed3r/21Updater/labels{/name}",
	  "releases_url": "https://api.github.com/repos/feed3r/21Updater/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/feed3r/21Updater/deployments",
	  "created_at": 1698966968,
	  "updated_at": "2024-03-03T10:09:05Z",
	  "pushed_at": 1713108971,
	  "git_url": "git://github.com/feed3r/21Updater.git",
	  "ssh_url": "git@github.com:feed3r/21Updater.git",
	  "clone_url": "https://github.com/feed3r/21Updater.git",
	  "svn_url": "https://github.com/feed3r/21Updater",
	  "homepage": null,
	  "size": 7809,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "Go",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": false,
	  "has_pages": false,
	  "has_discussions": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": {
		"key": "cc0-1.0",
		"name": "Creative Commons Zero v1.0 Universal",
		"spdx_id": "CC0-1.0",
		"url": "https://api.github.com/licenses/cc0-1.0",
		"node_id": "MDc6TGljZW5zZTY="
	  },
	  "allow_forking": true,
	  "is_template": false,
	  "web_commit_signoff_required": false,
	  "topics": [
  
	  ],
	  "visibility": "public",
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "main",
	  "stargazers": 0,
	  "master_branch": "main"
	},
	"pusher": {
	  "name": "feed3r",
	  "email": "feeder81@gmail.com"
	},
	"sender": {
	  "login": "feed3r",
	  "id": 4531376,
	  "node_id": "MDQ6VXNlcjQ1MzEzNzY=",
	  "avatar_url": "https://avatars.githubusercontent.com/u/4531376?v=4",
	  "gravatar_id": "",
	  "url": "https://api.github.com/users/feed3r",
	  "html_url": "https://github.com/feed3r",
	  "followers_url": "https://api.github.com/users/feed3r/followers",
	  "following_url": "https://api.github.com/users/feed3r/following{/other_user}",
	  "gists_url": "https://api.github.com/users/feed3r/gists{/gist_id}",
	  "starred_url": "https://api.github.com/users/feed3r/starred{/owner}{/repo}",
	  "subscriptions_url": "https://api.github.com/users/feed3r/subscriptions",
	  "organizations_url": "https://api.github.com/users/feed3r/orgs",
	  "repos_url": "https://api.github.com/users/feed3r/repos",
	  "events_url": "https://api.github.com/users/feed3r/events{/privacy}",
	  "received_events_url": "https://api.github.com/users/feed3r/received_events",
	  "type": "User",
	  "site_admin": false
	},
	"created": false,
	"deleted": true,
	"forced": false,
	"base_ref": null,
	"compare": "https://github.com/feed3r/21Updater/compare/6ab28d2aded0...000000000000",
	"commits": [
  
	],
	"head_commit": null
  }`
